environment: {}
parameters: {}
packages:
  - name: anvil
    environment:
      SPACES_ACCESS_KEY_ID: "${SPACES_ACCESS_KEY_ID}"
      SPACES_SECRET_ACCESS_KEY: "${SPACES_SECRET_ACCESS_KEY}"
      SPACES_BUCKET_NAME: "${SPACES_BUCKET_NAME}"
      RPCS: "${RPCS}"
      BASIC_AUTH_USER: "${BASIC_AUTH_USER}"
      BASIC_AUTH_PASSWORD: "${BASIC_AUTH_PASSWORD}"
    parameters: {}
    annotations: {}
    functions:
      - name: dump
        binary: false
        main: ''
        runtime: 'python:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
        triggers:
          - name: auto-dump
            sourceType: scheduler
            sourceDetails:
              cron: "*/10 * * * *"
      - name: load
        binary: false
        main: ''
        runtime: 'python:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
